name: Update Profile README

on:
  schedule:
    - cron: '0 0 */20 * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  

    - name: Get a random image
      id: random-image
      run: |
        IMAGES=($(ls images))
        RANDOM_IMAGE=${IMAGES[$RANDOM % ${#IMAGES[@]}]}
        echo "image=$RANDOM_IMAGE" >> $GITHUB_ENV  # Updated to use environment files

    - name: Update README
      run: |
        IMAGE_NAME=${{ env.image }}
        sed -i 's|<img src="images/.*" >|<img src="images/'"$IMAGE_NAME"'" >|' README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update profile image (automated)"
        git push
